# Generated by Django 4.1.7 on 2023-03-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'direction',
                'verbose_name_plural': 'directions',
            },
        ),
        migrations.CreateModel(
            name='StaffCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'staff_category',
                'verbose_name_plural': 'staff_categories',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee', to='staff.directionmodel')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.AddField(
            model_name='directionmodel',
            name='staff_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='staff.staffcategorymodel'),
        ),
    ]
