# Generated by Django 4.1.7 on 2023-03-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
