# Generated by Django 4.1.7 on 2023-03-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='is_information_added',
            field=models.BooleanField(default=False),
        ),
    ]
