# Generated by Django 4.1.7 on 2023-03-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='profile', to='user.citymodel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='zip_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
