# Generated by Django 4.1.7 on 2023-03-15 05:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_alter_servicemodel_price'),
        ('staff', '0002_employeemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diagnosis_history', to='service.servicemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'diagnosis_history',
                'verbose_name_plural': 'diagnosis_history',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('diagnosis', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='diagnosis.diagnosishistorymodel')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diagnosis', to='staff.employeemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'diagnosis',
                'verbose_name_plural': 'diagnosis',
            },
        ),
    ]
