# Generated by Django 4.1.7 on 2023-03-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosismodel',
            name='user',
        ),
    ]
