# Generated by Django 4.1.7 on 2023-03-16 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosis', '0002_remove_diagnosismodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
